import re
import string
from functools import lru_cache
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

try:
    STOP_WORDS = set(stopwords.words("indonesian"))
except LookupError:
    import nltk
    nltk.download("stopwords")
    STOP_WORDS = set(stopwords.words("indonesian"))

KEEP_WORDS = {
    "tidak", "tak", "bukan", "belum", "kurang", "jangan", "tanpa",
    "sangat", "banget", "sekali", "lebih", "paling", "baik", "bagus",
    "buruk", "jelek", "mantap", "cepat", "lambat", "oke", "ok"
}
CUSTOM_STOPWORDS = {
    'nya',
    'aja',
    'dong',
    'nih',
    'deh',
    'kok',
    'lah',
    'pun',
    'ya',
    'yah',
    'kan',
    'hehe',
    'wkwk',
    'wk',
    'haha',
    'hahaha',
    'dll',
    'dsb',
    'etc',
    'haduh',
    'waduh',
    'aduh',
    'jis',
    'job',
    'sen',
    'dah',
    'kek',
    'si',
    'mah',
    'ah',
    'an',
    'mu',
    'sih',
    'ter',
    'the',
    'pas',
    'up',
    'ku',
    'ni',
    'no'
}
STOP_WORDS = (STOP_WORDS - KEEP_WORDS) | CUSTOM_STOPWORDS

SLANG = {

    "gk":"tidak",
    "ga":"tidak",
    "gak":"tidak",
    "ngga":"tidak",
    "nggak":"tidak",
    "kga":"tidak",
    "kagak":"tidak",
    "tdk":"tidak",
    "tak":"tidak",

    "yg":"yang",
    "dg":"dengan",
    "dgn":"dengan",
    "dr":"dari",
    "drpd":"daripada",
    "utk":"untuk",
    "krn":"karena",
    "karna":"karena",
    "pd":"pada",
    "dlm":"dalam",
    "jd":"jadi",
    "jdi":"jadi",
    "trs":"terus",
    "trus":"terus",
    "tp":"tapi",
    "tpi":"tapi",
    "ato":"atau",
    "atoh":"atau",
    "klu":"kalau",
    "klo":"kalau",
    "kl":"kalau",

    "udh":"sudah",
    "udah":"sudah",
    "uda":"sudah",
    "sdh":"sudah",
    "blm":"belum",
    "blom":"belum",
    "blum":"belum",
    "msh":"masih",
    "masi":"masih",
    "skrng":"sekarang",
    "skrg":"sekarang",
    "kmrn":"kemarin",
    "bsk":"besok",

    "aja":"saja",
    "aj":"saja",
    "doang":"saja",
    "sm":"sama",
    "ama":"sama",
    "sy":"saya",
    "gw":"saya",
    "gua":"saya",
    "gue":"saya",
    "aq":"saya",
    "akuh":"saya",
    "km":"kamu",
    "loe":"kamu",
    "lu":"kamu",
    "bro":"saudara",
    "sis":"saudari",

    "bgt":"banget",
    "bngt":"banget",
    "bgtt":"banget",
    "bgttt":"banget",
    "bnget":"banget",
    "parahhh":"parah",
    "parahh":"parah",
    "bangett":"banget",
    "bangettt":"banget",

    "mantul":"mantap",
    "mantapp":"mantap",
    "mantappp":"mantap",
    "mantaaaap":"mantap",
    "jos":"bagus",
    "sip":"bagus",
    "kereeen":"keren",
    "kerennn":"keren",
    "bagusss":"bagus",
    "bagussss":"bagus",
    "ok":"oke",
    "okee":"oke",
    "okey":"oke",
    "good":"bagus",
    "best":"terbaik",
    "top":"bagus",

    "lemot":"lambat",
    "ngelag":"lambat",
    "lag":"lambat",
    "loading":"muat",
    "eror":"error",
    "erorr":"error",
    "errorrr":"error",
    "ngeload":"muat",
    "forceclose":"force close",
    "fc":"force close",
    "crash":"force close",
    "hang":"macet",
    "ngehang":"macet",
    "bugg":"bug",
    "buggy":"bug",

    "kecewaa":"kecewa",
    "kecewaa":"kecewa",
    "kesell":"kesal",
    "keselll":"kesal",
    "puass":"puas",
    "puasss":"puas",
    "seneng":"senang",
    "senengg":"senang",
    "sukaa":"suka",
    "sukaaa":"suka",

    "apk":"aplikasi",
    "app":"aplikasi",
    "apps":"aplikasi",
    "loginnya":"login",
    "loginnya":"login",
    "checkoutnya":"checkout",
    "checkot":"checkout",
    "ckout":"checkout",
    "co":"checkout",
    "paylater":"pay later",
    "spaylater":"shopee pay later",
    "shopepay":"shopee pay",
    "spay":"shopee pay",
    "codnya":"cod",
    "ongkirnya":"ongkir",
    "voucheran":"voucher",
    "vouchernya":"voucher",
    "diskonnya":"diskon",
    "cashbacknya":"cashback",
    "refundnya":"refund",

    "pengirimannya":"pengiriman",
    "pengirimn":"pengiriman",
    "ngirim":"kirim",
    "dikirimnya":"kirim",
    "sampe":"sampai",
    "ampe":"sampai",
    "nyampe":"sampai",
    "nyampenya":"sampai",
    "cepet":"cepat",
    "cepett":"cepat",
    "cepettt":"cepat",
    "lamaaa":"lama",
    "lamaaaa":"lama",
    "lambatt":"lambat",
    "lambattt":"lambat",

    "barangnya":"barang",
    "barangnyaa":"barang",
    "produknya":"produk",
    "sellernya":"seller",
    "tokonya":"toko",
    "packingnya":"packing",
    "packaging":"kemasan",
    "kemasannya":"kemasan",

    "murahhh":"murah",
    "murahh":"murah",
    "mahall":"mahal",
    "mahalhh":"mahal",

    "rekomen":"rekomendasi",
    "recommended":"rekomendasi",
    "recomended":"rekomendasi",
    "recomend":"rekomendasi",
    "worthit":"layak",
    "worth":"layak",

    "bner":"benar",
    "bnr":"benar",
    "dapet":"dapat",
    "dpet":"dapat",
    "gmn":"bagaimana",
    "gmna":"bagaimana",
    "knp":"kenapa",
    "kenap":"kenapa",
    "org":"orang",
    "pngn":"ingin",
    "pgn":"ingin",
    "udhla":"sudahlah",
    "smoga":"semoga",
    "moga":"semoga",
    "donlod" : "download",
    "hadeehhh" : "haduh",
    "benefitnya" : "benefit",
    "bgus" : "bagus",
    "bagu" : "bagus",
    "kalo" : "kalau",
    "utk" : "untuk",

    "ad" : "ada",
    "ahir" : "akhir",
    "ai" : "aku",
    "aing" : "aku",
    "aju" : "aku",
    "aju" : "aku",
    "akuu" : "aku",
    "burik" : "buruk",
    "boborok" : "buruk",
    "busuk" : "buruk",
    "appnya" : "aplikasi",
    "apus" : "hapus",
    "asa" : "asal",
    "atw" : "atau",
    "bad" : "buruk",
    "asw" : "buruk",
    "moga" : "semoga",
    "anjg" : "buruk",
    "banget" : "sangat",
    "apl" : "aplikasi",
    "bbrp" : "beberapa",
    "bbrpa" : "beberapa",

    "alam" : "akan",
    "alas" : "alat",
    "rb" : "ribu", 
    "tgl" : "tanggal",
    "gj" : "tidak jelas",
    "gajelas" : "tidak jelas",
    "shope" : "shopee",
    "shoope" : "shopee", 
    "shopi" : "shopee",
    "shopie" : "shopee",
    "tbtb" : "tiba-tiba",
    "bal" : "balas",
    "bales" : "balas",
    "balikin" : "mengembalikan",
    "lgi" : "lagi", 
    "passkw" : "tiruan",
    "beast" : "bagus",
    "bener" : "benar",
    "bgs" : "bagus",
    "bget" : "banget",
    "bgst" : "buruk",
    "bgtu" : "begitu",
    "barang" : "barang",
    "bnyk" : "banyak",
    "bru" : "baru",
    "bs" : "bisa",
    "bsa" : "bisa",
    "kuy" : "ayo",
    "tidal" : "tidak",
    "no" : "nomor",
    "shopinya" : "shopee",
    "dowlod" : "download",
    "lg" : "lagi",
    "hrus" : "harus",
    "make" : "memakai",
    "tlpn" : "telepon",
    "bntuanny" : "bantuan",
    "murmer" : "murah",
    "gercep" : "cepat",
    "lbh" : "lebih",
    "biar" : "agar",
    "tau" : "tahu"

}


STEMMER = StemmerFactory().create_stemmer()

@lru_cache(maxsize=50000)
def stem_word(word):
    return STEMMER.stem(word)

def preprocess_text(text):
    text = str(text).lower()
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)
    text = re.sub(r"@\w+", " ", text)
    text = re.sub(r"#(\w+)", r"\1", text)
    text = re.sub(r"\b\w*\d+\w*\b", " ", text)
    text = text.translate(str.maketrans("", "", string.punctuation))
    text = re.sub(r"[^a-zA-Z\s]", " ", text)
    text = re.sub(r"(.)\1{2,}", r"\1", text)
    text = re.sub(r"\s+", " ", text).strip()

    words = [SLANG.get(word, word) for word in text.split()]
    words = [word for word in words if word not in STOP_WORDS]
    words = [stem_word(word) for word in words]
    return " ".join(word for word in words if word).strip()
